apiVersion: v1
kind: Service
metadata:
  name: intelligent-weather-service
spec:
  type: LoadBalancer
  selector:
    app: intelligent-weather-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
